[build]
builder = "nixpacks"
buildCommand = "npm install && cd client && npm install && npm run build && cd ../server && npm install && npx prisma generate"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
